# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User'),
        ),
        migrations.AddField(
            model_name='context',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Plane'),
        ),
        migrations.AddField(
            model_name='context',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User'),
        ),
    ]
