# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20170627_1823'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Place',
        ),
        migrations.RemoveField(
            model_name='context',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='context',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='user',
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
        migrations.AddField(
            model_name='trip',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Place'),
        ),
        migrations.AddField(
            model_name='review',
            name='Trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Trip'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginreg.User'),
        ),
    ]
